-- | Per-program constructor tag assignment.
--
-- Assigns a deterministic integer tag to every constructor referenced in
-- a 'Program'.  Tags are computed by hashing the bare constructor name
-- (djb2 variant, mod 65521).  This makes tags /stable across modules/:
-- every compilation unit that references the same constructor gets the
-- same tag, which is critical for the self-hosted pipeline where values
-- constructed in one module (e.g. Consumer) are pattern-matched in
-- another (e.g. Perceus, Emitter).
--
-- The output is a @Map Text Int@ keyed on the bare constructor name
-- (@nameText . qnameName@), because bridges routinely emit
-- constructors with an empty module part and the intra-type dispatch
-- story means module qualification is not required for correctness.
module Frankenstein.Core.ConTags
  ( assignProgramTags
  , stableConTag
  , collectReferencedCtors
  , conKey
  ) where

import Frankenstein.Core.Types

import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Set (Set)
import qualified Data.Set as Set
import Data.Text (Text)
import qualified Data.Text as T

-- | The key used to look up a constructor in the tag table. Bridges
-- emit constructors inconsistently with respect to module qualification,
-- so we key on the bare name.
conKey :: QName -> Text
conKey qn = nameText (qnameName qn)

-- | Deterministic hash of a constructor name to a stable tag.
-- Uses a djb2-variant hash mod 65521 (largest prime < 2^16).
-- Every module that references the same constructor name gets the
-- same tag, enabling cross-module pattern matching in the self-hosted
-- pipeline.
stableConTag :: Text -> Int
stableConTag = (`mod` 65521) . abs . T.foldl' step 5381
  where step acc c = acc * 33 + fromEnum c

-- | Walk a 'Program' and assign a deterministic tag to every
-- constructor name referenced by 'DataDecl's, 'ECon' nodes, or
-- 'PatCon' patterns.  Tags are computed by 'stableConTag' (hash-based),
-- so they are stable across independently compiled modules.
--
-- Exception: Koka's @Cons@/@Nil@ constructors are built by the runtime
-- via 'kk_cons'/'kk_nil' (NOT 'kk_alloc_con'), so their cells carry the
-- hardcoded runtime constants @KK_CONS_TAG = 46589@ and
-- @KK_NIL_TAG = 31636@.  Pattern matches generated by the emitter
-- compare against the tag table; if we used 'stableConTag' for those
-- keys, the construction tag and the pattern tag would disagree and
-- every match would fall through to the default branch.  Override
-- those keys here so emitter and runtime agree.
assignProgramTags :: Program -> Map Text Int
assignProgramTags prog =
  let referenced = collectReferencedCtors prog
      -- Suffix-match instead of exact: Koka emits `Cons`/`Nil` patterns
      -- under several qualifier forms (e.g. "list/Cons", "core/Cons",
      -- "(::)") depending on the call site.  Detect the bare ctor
      -- name at the tail so we hit them all without enumerating.
      -- Mercury HLDS encodes constructor tags as "name/Arity"
      -- (@[]/0@, @./2@, @re_add/2@, @list_Cons/2@, etc.).  Strip the
      -- @/<digits>@ suffix before pattern-matching against the Cons/Nil
      -- specials so the bridge's switch arms hit the same fast-path
      -- runtime tags (kk_nil / kk_cons) the constructor side allocates.
      stripArity k = case T.breakOn "/" k of
        (prefix, rest)
          | not (T.null rest), T.all (\c -> c >= '0' && c <= '9') (T.drop 1 rest)
            -> prefix
        _ -> k
      tagFor k =
        let s = stripArity k
        in if endsWithCI "Cons" s || endsWith "(::)" s || endsWith "(:)" s
              || s == ":" || s == "."
           then kkConsTag
           else if endsWithCI "Nil" s || endsWith "[]" s || s == "[]"
                then kkNilTag
                else stableConTag k
      endsWith suf k =
        let n = T.length suf
        in T.length k >= n && T.takeEnd n k == suf
      -- Case-insensitive endsWith: Idris2's Linker mangles QNames like
      -- "_builtin/NIL" → "_builtin_NIL" (all-caps NIL/CONS); Haskell/Koka
      -- produce mixed-case "Nil"/"Cons".  Matching case-insensitively
      -- catches both without forcing every frontend to normalise.
      endsWithCI suf k =
        let n = T.length suf
        in T.length k >= n && T.toLower (T.takeEnd n k) == T.toLower suf
  in Map.fromList [(k, tagFor k) | k <- Set.toList referenced]

-- | Hardcoded runtime constructor tag for @Cons@ cells produced by
-- 'kk_cons' in @runtime/kk_runtime.c@.  Must stay in sync with
-- @KK_CONS_TAG@ in the C runtime.
kkConsTag :: Int
kkConsTag = 46589

-- | Hardcoded runtime constructor tag for @Nil@ cells produced by
-- 'kk_nil' in @runtime/kk_runtime.c@.  Must stay in sync with
-- @KK_NIL_TAG@ in the C runtime.
kkNilTag :: Int
kkNilTag = 31636

-- | Gather the set of constructor names referenced by a program.
-- Scans both 'DataDecl's (so declared ctors always appear, even if
-- unused) and every 'Expr' tree reachable from 'progDefs'.
--
-- The list comprehension is written as an explicit concatMap + map
-- chain rather than the nested @[ ... | x <- ..., y <- ... ]@ form
-- because GHC desugars the latter into a derived dictionary helper
-- that the Frankenstein Perceus pass over-drops on the outer-tail
-- argument (the recursive concatMap call gets a freed cell and
-- segfaults on its tag read).  The explicit form goes through
-- standard concatMap/map which Perceus handles correctly.
collectReferencedCtors :: Program -> Set Text
collectReferencedCtors prog =
  let dataDecls = progData prog
      ctorNames = concatMap (\dd -> map (conKey . conName) (dataCons dd)) dataDecls
      fromData  = Set.fromList ctorNames
      fromDefs  = Set.unions (map (ctorsInExpr . defExpr) (progDefs prog))
  in fromData `Set.union` fromDefs

-- | Recursively collect every constructor name referenced by an
-- expression — both as 'ECon' / 'EApp (ECon _) _' and inside
-- 'PatCon' patterns.
ctorsInExpr :: Expr -> Set Text
ctorsInExpr expr = go expr
  where
    go (ECon qn)           = Set.singleton (conKey qn)
    go (EVar _)            = Set.empty
    go (ELit _)            = Set.empty
    go (EFunRef _)         = Set.empty
    go (EApp f args)       = Set.unions (go f : map go args)
    go (ELam _ body)       = go body
    go (ELet bgs body)     =
      -- Explicit concatMap form (see commit a5a578c).
      Set.unions (go body : concatMap (map (go . bindExpr)) bgs)
    go (ECase scrut bs)    =
      Set.unions (go scrut : map branch bs)
    go (ETypeApp e _)      = go e
    go (ETypeLam _ e)      = go e
    go (EPerform _ args)   = Set.unions (map go args)
    go (EHandle _ h b)     = go h `Set.union` go b
    go (ERetain e)         = go e
    go (ERelease e)        = go e
    go (EDrop e)           = go e
    go (EReuse e1 e2)      = go e1 `Set.union` go e2
    go (EDelay e)          = go e
    go (EForce e)          = go e

    branch (Branch pat mg body) =
      Set.unions [pat' pat, maybe Set.empty go mg, go body]

    pat' (PatCon qn subs) =
      Set.insert (conKey qn) (Set.unions (map pat' subs))
    pat' (PatVar _ _)     = Set.empty
    pat' (PatWild _)      = Set.empty
    pat' (PatLit _)       = Set.empty
