module SinglePatCon where

-- Pattern class: case with exactly ONE branch using PatCon.
-- Equivalent shape to record-field selectors (auto-generated by deriveSelectors).
--
-- Expected: classifyBranches → SingleConCase
-- Observed bug: stage-1 binary emits ConCase-with-default (tag check + scf.if).

data Pair = Pair Int Int

getSnd :: Pair -> Int
getSnd p = case p of
  Pair _ y -> y

main :: Int
main = getSnd (Pair 1 42)
-- Expect: 42
